# Site settings
baseurl = "https://works.vltraheaven.io/"
languageCode = "en-us"
title = "⚡ Vltraheaven Works ⚡"
description = "Masters in bridging the gap between people and technology."
theme = "hugo-artists-theme"

[params]

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Vltraheaven Works"
	description = "Bridging the gap between people and technology."

	email = "contact@vltraheaven.io"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "VltraHeaven Works"
		shortBio = "Computer Repair // DevOps // Programming // System Administration"

	[params.about]
		title = "About"
		bio = "**Subject matter expertise without the ego.** As technology continues to grow in variety and complexity, my focus remains translating enterprise-class tech solutions for the every-person."

		[[params.about.skills]]
			name = "Communication"
			value = 10

		[[params.about.skills]]
			name = "Continuous Integration"
			value = 7

		[[params.about.skills]]
			name = "Linux Server Administration"
			value = 8

		[[params.about.skills]]
			name = "Windows Server Administraton"
			value = 7

		[[params.about.skills]]
			name = "Version Control"
			value = 5

		[[params.about.skills]]
			name = "System Hardening"
			value = 7

		[[params.about.skills]]
			name = "Containers/Virtualization"
			value = 8

		[[params.about.skills]]
			name = "Vulnerability Testing"
			value = 6

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/vltraheaven"

		[[params.contact.social]]
			icon = "github"
			link = "//github.com/VltraHeaven"

        [[params.contact.social]]
			icon = "linkedin"
            link = "//linkedin.com/in/julio-hawthorne-2b2611b8"

	[params.form]
		title = "Contact"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your issue/project"
		buttonText = "Send"


	[params.footer]
		copyright = "【VLTRAHEAVEN】 © 2019"
