# Site settings
baseurl = "https://works.vltraheaven.io/"
languageCode = "en-us"
title = "⚡ Vltraheaven Works ⚡"
description = "Masters in bridging the gap between people and technology."
theme = "hugo-artists-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Vltraheaven Works"
	description = "Bridging the gap between people and technology."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@vltraheaven.io"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "VltraHeaven Works"
		shortBio = "Development // Security // Administration"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About"
		bio = "**Subject matter expertise without the ego.** As technology continues to grow in variety and complexity, my focus remains translating enterprise-class tech solutions for the every-person."

		[[params.about.skills]]
			name = "Communication"
			value = 10

		[[params.about.skills]]
			name = "Web Development"
			value = 7

		[[params.about.skills]]
			name = "Linux Administration"
			value = 8

		[[params.about.skills]]
			name = "Windows Administraton"
			value = 7

		[[params.about.skills]]
			name = "Software Development"
			value = 5

		[[params.about.skills]]
			name = "System Hardening"
			value = 7

		[[params.about.skills]]
			name = "Vulnerability Assessment"
			value = 8

		[[params.about.skills]]
			name = "Penetration Testing"
			value = 6

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/vltraheaven"

		[[params.contact.social]]
			icon = "github"
			link = "//github.com/VltraHeaven"

        [[params.contact.social]]
			icon = "linkedin"
            link = "//linkedin.com/in/julio-hawthorne-2b2611b8"

	[params.form]
		title = "Contact"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your issue/project"
		buttonText = "Send"


	[params.footer]
		copyright = "【VLTRAHEAVEN】 © 2019"
